<PlaygroundQuery
  id="get_poc_data"
  adhocResourceType={null}
  data={null}
  resourceType="retoolDb"
>
  <SqlQuery
    _additionalScope={[]}
    actionType=""
    allowedGroupIds={[]}
    allowedGroups={[]}
    bulkUpdatePrimaryKey=""
    dataArray={[]}
    doNotThrowOnNoOp={false}
    editorMode="sql"
    enableBulkUpdates={false}
    events={[]}
    filterBy=""
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    query={include("./lib/get_poc_data.sql", "string")}
    recordId=""
    records=""
    showUpdateSetValueDynamicallyToggle={false}
    tableName=""
    updateSetValueDynamically={true}
    warningCodes={[]}
    watchedParams={[]}
  />
</PlaygroundQuery>
